### ISSUE TITLE
Bad permissions on google_apputils.egg-info

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/google-apputils#4]
```
ls -la google_apputils.egg-info
total 56
drwxr-x---   9 schwehr  eng   306 Feb 29  2012 .
drwxr-x---  11 schwehr  eng   374 Feb 29  2012 ..
-rw-r-----   1 schwehr  eng   247 Feb 29  2012 PKG-INFO
-rw-r-----   1 schwehr  eng  1032 Feb 29  2012 SOURCES.txt
-rw-r-----   1 schwehr  eng     1 Feb 29  2012 dependency_links.txt
-rw-r-----   1 schwehr  eng   175 Feb 29  2012 entry_points.txt
-rw-r-----   1 schwehr  eng    23 Feb 29  2012 namespace_packages.txt
-rw-r-----   1 schwehr  eng    53 Feb 29  2012 requires.txt
-rw-r-----   1 schwehr  eng     7 Feb 29  2012 top_level.txt


Missing r-x and r-- for dir and files.  So python's install process can write 
into a tree as one user (e.g. root) and block other setup.py's from working.



What steps will reproduce the problem?
1.
2.
3.

What is the expected output? What do you see instead?


bigquery-2.0.12/table_formatter.py
sudo -u fink-bld [ENV] sh -c /tmp/fink.4ugD2
perl -pi -e "s/'google-api-python-client==.*',//" setup.py
perl -pi -e "s/'oauth2client==.*',//" setup.py
/sw/bin/python2.7 setup.py build
Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    use_setuptools()
  File "/sw/src/fink.build/bigquery-py27-2.0.12-1/bigquery-2.0.12/ez_setup.py", line 74, in use_setuptools
    import pkg_resources
  File "/sw/lib/python2.7/site-packages/pkg_resources.py", line 2825, in <module>
    add_activation_listener(lambda dist: dist.activate())
  File "/sw/lib/python2.7/site-packages/pkg_resources.py", line 710, in subscribe
    callback(dist)
  File "/sw/lib/python2.7/site-packages/pkg_resources.py", line 2825, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/sw/lib/python2.7/site-packages/pkg_resources.py", line 2257, in activate
    self.insert_on(path)
  File "/sw/lib/python2.7/site-packages/pkg_resources.py", line 2364, in insert_on
    self.check_version_conflict()
  File "/sw/lib/python2.7/site-packages/pkg_resources.py", line 2401, in check_version_conflict
    nsp = dict.fromkeys(self._get_metadata('namespace_packages.txt'))
  File "/sw/lib/python2.7/site-packages/pkg_resources.py", line 2251, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/sw/lib/python2.7/site-packages/pkg_resources.py", line 1219, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/sw/lib/python2.7/site-packages/pkg_resources.py", line 1211, in get_metadata
    return self._get(self._fn(self.egg_info,name))
  File "/sw/lib/python2.7/site-packages/pkg_resources.py", line 1326, in _get
    stream = open(path, 'rb')
IOError: [Errno 13] Permission denied: 
'/sw/lib/python2.7/site-packages/google_apputils-0.3.0-py2.7.egg-info/namespace_
packages.txt'
### execution of /sw/bin/python2.7 failed, exit code 1
### execution of /tmp/fink.4ugD2 failed, exit code 1

What version of the product are you using? On what operating system?

fink mac osx 10.8

Please provide any additional information below.


```

Original issue reported on code.google.com by `schw...@gmail.com` on 15 May 2013 at 9:37

**Comment by gpshead** [comment]
We won't be fixing issues directly in this repository.  Development of this library has been moved to https://github.com/abseil/abseil-py.  If it can be reproduced there, please open an issue in the abseil-py project.
